#!/usr/bin/env python3
"""
generate_movies_sql.py
======================
Reads ott_movies_clean_unique.csv and emits data.sql containing INSERT
statements for the StayAnalytics schema:

  platform, genre, content, tag, content_tag, users, review, watchlist

Run:
    python3 scripts/generate_movies_sql.py

Inputs:
    ott_movies_clean_unique.csv   (project root)

Outputs:
    data.sql                      (project root)

The script also seeds 3 demo accounts (BCrypt-hashed passwords) and
generates ~5,000 reviews + ~500 watchlist rows so the analytics dashboard
and aggregate queries are non-trivial during the demo.
"""
import csv
import os
import random
from pathlib import Path

ROOT       = Path(__file__).resolve().parent.parent
CSV_PATH   = ROOT / "ott_movies_clean_unique.csv"
OUT_PATH   = ROOT / "data.sql"

# Pre-computed BCrypt hashes (strength 12). Plaintext passwords are
# documented in readme.txt for grading.
DEMO_USERS = [
    # username, email, password_hash, role, plaintext (for readme only)
    ("admin",  "admin@stayanalytics.com",
     "$2b$12$7D4X/Gx.zjXXhuFEsWEWaOqnnRq1amfWirtITJQfBPs7pvLxO70Iq",
     "ADMIN", "Demo1!"),
    ("alice",  "alice@example.com",
     "$2b$12$RMlrOATVl6/Jte1To66PXePq.cLwuVEue4R4WyDmGMfzU7L.PyfUO",
     "USER",  "Demo2!"),
    ("bob",    "bob@example.com",
     "$2b$12$tfCxrtU67TY5If9kQXCjkOs1NuqLbDk0T6BJ.DXKZzG/.Tq5pmjNq",
     "USER",  "Demo3!"),
]

NUM_REVIEWS    = 5000
NUM_WATCHLIST  = 500
RANDOM_SEED    = 4400

REVIEW_COMMENTS = [
    "Loved the cinematography and pacing.",
    "A bit slow in the middle but ended strong.",
    "Top-tier acting from the lead.",
    "Could have used a tighter script.",
    "Binge-worthy from start to finish.",
    "The soundtrack stole the show.",
    "Great premise, mediocre execution.",
    "One of my favorites this year.",
    "Predictable plot but enjoyable.",
    "Underrated gem on this platform.",
    "The finale was unforgettable.",
    "Wouldn't rewatch but glad I saw it.",
    "Solid weekend pick.",
    "Beautiful visuals, weak character arcs.",
    "Surprisingly emotional.",
]


def sql_str(s):
    """Quote a string for SQL: escape single quotes and backslashes."""
    if s is None:
        return "NULL"
    return "'" + str(s).replace("\\", "\\\\").replace("'", "''") + "'"


def sql_num(s):
    if s is None or s == "":
        return "NULL"
    return str(s)


def split_tags(raw):
    if not raw:
        return []
    cleaned = raw.strip().strip('"').strip("'")
    return [t.strip() for t in cleaned.split(",") if t.strip()]


def main():
    if not CSV_PATH.exists():
        raise SystemExit(f"CSV not found: {CSV_PATH}")

    random.seed(RANDOM_SEED)

    # Pass 1: read CSV and collect distinct platforms/genres/tags
    rows = []
    platforms = {}   # name -> id (assigned later)
    genres    = {}
    tags      = {}

    with CSV_PATH.open(newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for r in reader:
            rows.append(r)
            platforms.setdefault(r["platform"], None)
            genres.setdefault(r["genre"], None)
            for t in split_tags(r["tags"]):
                tags.setdefault(t, None)

    # Assign deterministic IDs (sorted for reproducibility)
    for i, name in enumerate(sorted(platforms), start=1):
        platforms[name] = i
    for i, name in enumerate(sorted(genres), start=1):
        genres[name] = i
    for i, name in enumerate(sorted(tags), start=1):
        tags[name] = i

    out_lines = []
    out_lines.append("-- =====================================================================")
    out_lines.append("-- StayAnalytics — data.sql (generated by scripts/generate_movies_sql.py)")
    out_lines.append("-- Loads platforms, genres, content (2,500 rows), tags, demo users,")
    out_lines.append(f"-- {NUM_REVIEWS} reviews, and {NUM_WATCHLIST} watchlist rows.")
    out_lines.append("-- =====================================================================")
    out_lines.append("USE stayanalytics;")
    out_lines.append("SET FOREIGN_KEY_CHECKS = 0;")
    out_lines.append("TRUNCATE TABLE content_tag;")
    out_lines.append("TRUNCATE TABLE tag;")
    out_lines.append("TRUNCATE TABLE watchlist;")
    out_lines.append("TRUNCATE TABLE review;")
    out_lines.append("TRUNCATE TABLE content;")
    out_lines.append("TRUNCATE TABLE genre;")
    out_lines.append("TRUNCATE TABLE platform;")
    out_lines.append("TRUNCATE TABLE users;")
    out_lines.append("SET FOREIGN_KEY_CHECKS = 1;")
    out_lines.append("")

    # Platforms
    out_lines.append("-- platform")
    for name, pid in sorted(platforms.items(), key=lambda kv: kv[1]):
        out_lines.append(
            f"INSERT INTO platform (platform_id, name) VALUES ({pid}, {sql_str(name)});"
        )
    out_lines.append("")

    # Genres
    out_lines.append("-- genre")
    for name, gid in sorted(genres.items(), key=lambda kv: kv[1]):
        out_lines.append(
            f"INSERT INTO genre (genre_id, name) VALUES ({gid}, {sql_str(name)});"
        )
    out_lines.append("")

    # Tags
    out_lines.append("-- tag")
    for name, tid in sorted(tags.items(), key=lambda kv: kv[1]):
        out_lines.append(
            f"INSERT INTO tag (tag_id, name) VALUES ({tid}, {sql_str(name)});"
        )
    out_lines.append("")

    # Content (batched)
    out_lines.append("-- content (2,500 rows)")
    BATCH = 100
    content_ids = []
    for i in range(0, len(rows), BATCH):
        chunk = rows[i:i + BATCH]
        values = []
        for r in chunk:
            content_ids.append(r["content_id"])
            values.append(
                "({cid}, {title}, {ctype}, {pid}, {gid}, {country}, {lang}, "
                "{year}, {dur}, {rating}, {votes}, {weighted}, {eng}, {pop}, "
                "{trend}, {desc}, {poster})".format(
                    cid=sql_str(r["content_id"]),
                    title=sql_str(r["title"]),
                    ctype=sql_str(r["type"]),
                    pid=platforms[r["platform"]],
                    gid=genres[r["genre"]],
                    country=sql_str(r["country"]),
                    lang=sql_str(r["language"]),
                    year=sql_num(r["release_year"]),
                    dur=sql_num(r["duration_minutes"]),
                    rating=sql_num(r["rating"]),
                    votes=sql_num(r["votes"]),
                    weighted=sql_num(r["weighted_rating"]),
                    eng=sql_num(r["engagement_score"]),
                    pop=sql_num(r["popularity_score"]),
                    trend=sql_num(r["trending_score"]),
                    desc=sql_str(r["description"]),
                    poster=sql_str(r["poster_url"]),
                )
            )
        out_lines.append(
            "INSERT INTO content (content_id, title, type, platform_id, genre_id, "
            "country, language, release_year, duration_minutes, imdb_rating, votes, "
            "weighted_rating, engagement_score, popularity_score, trending_score, "
            "description, poster_url) VALUES\n  " + ",\n  ".join(values) + ";"
        )
    out_lines.append("")

    # content_tag
    out_lines.append("-- content_tag")
    ct_pairs = []
    for r in rows:
        for t in split_tags(r["tags"]):
            ct_pairs.append((r["content_id"], tags[t]))
    for i in range(0, len(ct_pairs), 500):
        chunk = ct_pairs[i:i + 500]
        values = ", ".join(f"({sql_str(c)}, {t})" for c, t in chunk)
        out_lines.append(
            f"INSERT INTO content_tag (content_id, tag_id) VALUES {values};"
        )
    out_lines.append("")

    # Users
    out_lines.append("-- users (demo accounts)")
    for i, (uname, email, pwhash, role, _plain) in enumerate(DEMO_USERS, start=1):
        out_lines.append(
            f"INSERT INTO users (user_id, username, email, password_hash, role) "
            f"VALUES ({i}, {sql_str(uname)}, {sql_str(email)}, {sql_str(pwhash)}, {sql_str(role)});"
        )
    out_lines.append("")

    # Reviews
    out_lines.append(f"-- review ({NUM_REVIEWS} synthetic rows)")
    user_ids = list(range(1, len(DEMO_USERS) + 1))
    chosen_pairs = set()
    review_rows = []
    while len(review_rows) < NUM_REVIEWS:
        uid = random.choice(user_ids)
        cid = random.choice(content_ids)
        if (uid, cid) in chosen_pairs:
            continue
        chosen_pairs.add((uid, cid))
        rating = random.choices(
            population=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
            weights=[1, 1, 2, 3, 5, 8, 12, 18, 25, 25],
            k=1,
        )[0]
        comment = random.choice(REVIEW_COMMENTS)
        review_rows.append((uid, cid, rating, comment))

    for i in range(0, len(review_rows), 500):
        chunk = review_rows[i:i + 500]
        values = ", ".join(
            f"({uid}, {sql_str(cid)}, {rating}, {sql_str(comment)})"
            for uid, cid, rating, comment in chunk
        )
        out_lines.append(
            "INSERT INTO review (user_id, content_id, rating, comment) "
            f"VALUES {values};"
        )
    out_lines.append("")

    # Watchlist
    out_lines.append(f"-- watchlist ({NUM_WATCHLIST} synthetic rows)")
    statuses = ["PLAN_TO_WATCH", "WATCHING", "WATCHED"]
    wl_pairs = set()
    wl_rows = []
    while len(wl_rows) < NUM_WATCHLIST:
        uid = random.choice(user_ids)
        cid = random.choice(content_ids)
        if (uid, cid) in wl_pairs:
            continue
        wl_pairs.add((uid, cid))
        wl_rows.append((uid, cid, random.choice(statuses)))

    for i in range(0, len(wl_rows), 500):
        chunk = wl_rows[i:i + 500]
        values = ", ".join(
            f"({uid}, {sql_str(cid)}, {sql_str(status)})"
            for uid, cid, status in chunk
        )
        out_lines.append(
            "INSERT INTO watchlist (user_id, content_id, status) "
            f"VALUES {values};"
        )
    out_lines.append("")

    OUT_PATH.write_text("\n".join(out_lines) + "\n", encoding="utf-8")
    print(f"Wrote {OUT_PATH}")
    print(f"  platforms:    {len(platforms)}")
    print(f"  genres:       {len(genres)}")
    print(f"  content rows: {len(rows)}")
    print(f"  tags:         {len(tags)}")
    print(f"  content_tag:  {len(ct_pairs)}")
    print(f"  users:        {len(DEMO_USERS)}")
    print(f"  reviews:      {len(review_rows)}")
    print(f"  watchlist:    {len(wl_rows)}")


if __name__ == "__main__":
    main()
